### PR TITLE
Add glassmorphism effect to transparent panels

### PR DESCRIPTION
**Pull request by Double-A-92**
I tried to make the main view a bit nicer by making the transparent objects look like glass.

Before:
image

After: 
image

### CODE REVIEW

**Comment by Austin077** [comment]
That's an awesome idea, and we'll take it on board. 
But there is another small suggestion: the stroke above the background of the widget will make the card less clean, can you remove the stroke to keep a clean background?

**Comment by zhanghengxin** [comment]
> That's an awesome idea, and we'll take it on board. But there is another small suggestion: the stroke above the background of the widget will make the card less clean, can you remove the stroke to keep a clean background?

@Double-A-92 

1、Can you resubmit according to the designer's request?
2、Can you submit to the feature branch?

**Comment by Double-A-92** [comment]
@Austin077 I tried completely removing it, but it also removes the "realistic" glass effect because there is no depth. I also created a new version making the edge as subtle as possible. 

New subtle version: 
image

Edge completely removed:
image

Are you really sure? If yes, I will commit the version you request :)

**Comment by Austin077** [comment]
> New subtle version
Your "New subtle version" is very cool, we'll take it on board and ask you to submit a new version.
The fading of the stroke is simple and elegant, and the overall integration of the interface is much better, thank you!

**Comment by Double-A-92** [comment]
Thank you. 
I will create a new fresh pull request, because this one kinda got messed up somehow while changing branches...

**Pull request merged**
